### ISSUE TITLE
many errors when i installed the package ?

### ISSUE THREAD

**Issue by mohammedmatar** [dan335/meteor-user-presence#1]
`Exception from sub id undefined Error: After filtering out keys not in the schema, your modifier is now empty
  at [object Object].doValidate (packages/aldeed:collection2-core/collection2.js:389:11)
  at [object Object].Mongo.Collection.(anonymous function) [as update] 
  (packages/aldeed:collection2-core/collection2.js:187:25)
  at trackUserStatus (packages/danimal:userpresence/userPresence.js:92:16)
`
i think we need to extend User collection with new Schema

**Comment by mohammedmatar** [comment]
i fix it by adding:

> presence { type: Object, blackbox: true }

to my users collection's schema.

**Comment by dan335** [comment]
So you fixed the error you had?  Can close issue?  Do you get errors when not using aldeed:collection2?

**Comment by mohammedmatar** [comment]
>  @dan335  So you fixed the error you had? Can close issue? Do you get errors when not using aldeed:collection2?

yes i fixed it !.
the errors just show up because i didn't Update Meteor.users collection with presence Object.

Thank You very much, your package is very helpful and very easy to use.
